"""Error-CDF figure for the UNCONDITIONED SVR. SUPERSEDED.

The article reports the region-conditioned localiser (Section 3), whose errors
are smaller throughout. Figure 3 is generated by region_errors.py followed by
replot_region.py; this script is retained only because the coarse hyperparameter
grid of Appendix A was searched upon the unconditioned instrument.

Error-CDF figure: the effect of evaluation protocol on reported accuracy.

Protocol -> colour (categorical slots 1-3, all-pairs validated)
Method   -> line style (solid SVR / dashed kNN), so identity survives grayscale
            printing and colour-vision deficiency without relying on hue.
"""
import json
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GroupShuffleSplit
from sklearn.neighbors import KNeighborsRegressor

from corrected_pipeline import fit_predict
from uji_data import load_uji, features, targets, error_2d

C, GAMMA, EPS = 10, 2e-5, 0.1
COL = {"A": "#2a78d6", "C": "#eb6834", "B": "#199e70"}
LABEL = {"A": "A  random split", "C": "C  RP-disjoint", "B": "B  device/time holdout"}

tr, va = load_uji()
X, Xv = features(tr, "raw"), features(va, "raw")
xt, yt = targets(tr)
xv, yv = targets(va)
_, groups = np.unique(tr[:, [520, 521, 522]], axis=0, return_inverse=True)

err = {}

# Protocol A -- random split
i_tr, i_te = train_test_split(np.arange(len(tr)), test_size=0.2, random_state=42)
px = fit_predict(X[i_tr], xt[i_tr], X[i_te], C, GAMMA, EPS)
py = fit_predict(X[i_tr], yt[i_tr], X[i_te], C, GAMMA, EPS)
err[("SVR", "A")] = error_2d(xt[i_te], yt[i_te], px, py)
k = KNeighborsRegressor(3).fit(X[i_tr], np.c_[xt[i_tr], yt[i_tr]]).predict(X[i_te])
err[("kNN", "A")] = error_2d(xt[i_te], yt[i_te], k[:, 0], k[:, 1])
print("A done", flush=True)

# Protocol C -- reference-point-disjoint
i_tr, i_te = next(GroupShuffleSplit(1, test_size=0.2, random_state=0).split(X, xt, groups))
assert not (set(groups[i_te]) & set(groups[i_tr]))
px = fit_predict(X[i_tr], xt[i_tr], X[i_te], C, GAMMA, EPS)
py = fit_predict(X[i_tr], yt[i_tr], X[i_te], C, GAMMA, EPS)
err[("SVR", "C")] = error_2d(xt[i_te], yt[i_te], px, py)
k = KNeighborsRegressor(3).fit(X[i_tr], np.c_[xt[i_tr], yt[i_tr]]).predict(X[i_te])
err[("kNN", "C")] = error_2d(xt[i_te], yt[i_te], k[:, 0], k[:, 1])
print("C done", flush=True)

# Protocol B -- official holdout
px = fit_predict(X, xt, Xv, C, GAMMA, EPS)
py = fit_predict(X, yt, Xv, C, GAMMA, EPS)
err[("SVR", "B")] = error_2d(xv, yv, px, py)
k = KNeighborsRegressor(3).fit(X, np.c_[xt, yt]).predict(Xv)
err[("kNN", "B")] = error_2d(xv, yv, k[:, 0], k[:, 1])
print("B done", flush=True)

json.dump({f"{m}_{p}": np.asarray(v).tolist() for (m, p), v in err.items()},
          open("out_errors.json", "w"))

# ----------------------------------------------------------------- figure
plt.rcParams.update({
    "font.family": "serif", "font.size": 7.2,
    "axes.linewidth": 0.5, "xtick.major.width": 0.5, "ytick.major.width": 0.5,
    "xtick.labelsize": 6.8, "ytick.labelsize": 6.8,
})
fig, axes = plt.subplots(2, 1, figsize=(3.5, 3.9), sharex=True)

for ax, method in zip(axes, ("SVR", "kNN")):
    for prot in ("A", "C", "B"):
        e = np.sort(np.asarray(err[(method, prot)]))
        cdf = np.arange(1, e.size + 1) / e.size
        ax.plot(e, cdf, color=COL[prot], lw=1.3,
                ls="-" if method == "SVR" else (0, (4, 1.6)),
                label=LABEL[prot], solid_capstyle="round")
        # direct label at the 60th percentile -- discharges the contrast relief rule
        xi = float(np.percentile(e, 60))
        ax.annotate(prot, xy=(xi, 0.60), xytext=(2.5, -6.5),
                    textcoords="offset points", color=COL[prot],
                    fontsize=7.4, fontweight="bold")
    ax.set_xlim(0, 60)
    ax.set_ylim(0, 1.02)
    ax.grid(True, lw=0.35, color="#d8d8d4", alpha=0.9)
    ax.set_axisbelow(True)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    ax.set_ylabel("fraction of samples")
    ax.text(0.975, 0.08, method, transform=ax.transAxes, ha="right",
            fontsize=8.2, fontweight="bold", color="#0b0b0b")

axes[1].set_xlabel("2D positioning error (m)")
axes[0].legend(loc="lower right", frameon=False, fontsize=6.4,
               handlelength=2.4, borderaxespad=0.4, labelspacing=0.32)
fig.align_ylabels(axes)
fig.tight_layout(pad=0.35, h_pad=0.7)
fig.savefig("protocol_cdf.pdf", bbox_inches="tight")
fig.savefig("protocol_cdf.png", dpi=200, bbox_inches="tight")
print("wrote protocol_cdf.pdf / .png")

for (m, p), v in sorted(err.items()):
    v = np.asarray(v)
    print(f"  {m:4s} {p}: MAE={v.mean():6.2f}  median={np.median(v):6.2f}  n={v.size}")
